---
- name: Update debian
  hosts: debian
  tasks:
     - name: update
       command: "apt update -y"

     - name: upgrade
       command: "apt upgrade -y"

     - name: dist-upgrade
       command: "apt dist-upgrade -y"

     - name: autoremove
       command: "apt autoremove -y"

     - name: autoclean
       command: "apt autoclean -y" 
